### ISSUE TITLE
Touch (and other things?) don't work as of b36cb49

### ISSUE THREAD

**Issue by litui** [Xinyuan-LilyGO/T-Display-S3-Pro#5]
Using PlatformIO to build, there are incompatibilities with the touch code that prevent compile.

After changing touch.init to touch.begin in several examples, touch still doesn't work. I had to revert to a past commit to find examples where touch actually works.

Please refresh this repository with working example code, thank you.

**Comment by litui** [comment]
4d5bf77 is the last build that works for me in PlatformIO. It looks like the updates to dependencies in 8a77996 broke the build.

**Comment by lewisxhe** [comment]
Which example did you use?

**Comment by lewisxhe** [comment]
Fixed, please try again

**Comment by litui** [comment]
Confirmed working. Thanks, @lewisxhe.
